Repository lablup/backend.ai-storage-proxy, pull requests merged in 2022-03, with the labels that each got.

#38 refactor: Split out vfolder creation from vfolder clone
  changes/38.fix.md
  src/ai/backend/storage/abc.py
  src/ai/backend/storage/netapp/__init__.py
  src/ai/backend/storage/types.py
  src/ai/backend/storage/vfs/__init__.py
  src/ai/backend/storage/xfs/__init__.py
Labels: refactor

#40 feat: Add the move-file manager-facing API
  changes/40.feature.md
  src/ai/backend/storage/abc.py
  src/ai/backend/storage/api/manager.py
Labels: feature

#41 feat: Add subpath check to the get_vfolder_mount API for early failure
  changes/41.feature.md
  src/ai/backend/storage/abc.py
  src/ai/backend/storage/api/manager.py
  src/ai/backend/storage/exception.py
  src/ai/backend/storage/netapp/__init__.py
  src/ai/backend/storage/purestorage/__init__.py
  src/ai/backend/storage/vfs/__init__.py
  src/ai/backend/storage/xfs/__init__.py
Labels: feature, refactor

#35 feat: update sample.toml and readme for better initialization
  README.md
  changes/35.misc.md
  config/sample.toml
Labels: docs, good first issue

#42 setup,ci: Set the required Python version to 3.10
  .github/workflows/default.yml
  .github/workflows/timeline-check.yml
  changes/42.breaking.md
  setup.cfg
Labels: maintenance
